[control_plane]
cp01 ansible_host=192.168.10.11 k8s_hostname=cp01.company.local node_ip=192.168.10.11 keepalived_state=MASTER keepalived_priority=100
cp02 ansible_host=192.168.10.12 k8s_hostname=cp02.company.local node_ip=192.168.10.12 keepalived_state=BACKUP keepalived_priority=90
cp03 ansible_host=192.168.10.13 k8s_hostname=cp03.company.local node_ip=192.168.10.13 keepalived_state=BACKUP keepalived_priority=80

[workers]
worker01 ansible_host=192.168.10.21 k8s_hostname=worker01.company.local node_ip=192.168.10.21
worker02 ansible_host=192.168.10.22 k8s_hostname=worker02.company.local node_ip=192.168.10.22
worker03 ansible_host=192.168.10.23 k8s_hostname=worker03.company.local node_ip=192.168.10.23

[k8s_nodes:children]
control_plane
workers

[all:vars]
ansible_python_interpreter=/usr/bin/python3
